using Newtonsoft.Json.Linq;

namespace CrystalEditor.Core
{
    public enum ItemCategory
    {
        Weapon, Armor, Item
    }

    public enum ItemType
    {
        WEAPON_SWORD = 1,
        WEAPON_HAMMER = 2,
        WEAPON_AXE = 3,
        WEAPON_DAGGER = 4,
        WEAPON_ROD = 5,
        WEAPON_SWORD_V = 6,
        WEAPON_SWORD_S = 7,
        WEAPON_SWORD_Q = 8,
        WEAPON_SWORD_V_S = 9,
        WEAPON_SWORD_S_Q = 10,
        WEAPON_SWORD_Q_D = 11,
        WEAPON_SWORD_FIRE = 12,
        WEAPON_SWORD_BLIZ = 13,
        WEAPON_SWORD_THUN = 14,
        WEAPON_HAMMER_S = 15,
        WEAPON_HAMMER_E = 16,
        WEAPON_HAMMER_I = 17,
        WEAPON_HAMMER_F = 18,
        WEAPON_HAMMER_S_E = 19,
        WEAPON_HAMMER_E_Q = 20,
        WEAPON_HAMMER_I_D = 21,
        WEAPON_HAMMER_F_E = 22,
        WEAPON_HAMMER_FIRE = 23,
        WEAPON_HAMMER_BLIZ = 24,
        WEAPON_HAMMER_THUN = 25,
        WEAPON_AXE_V = 26,
        WEAPON_AXE_D = 27,
        WEAPON_AXE_F = 28,
        WEAPON_AXE_V_I = 29,
        WEAPON_AXE_D_Q = 30,
        WEAPON_AXE_F_S = 31,
        WEAPON_AXE_FIRE = 32,
        WEAPON_AXE_BLIZ = 33,
        WEAPON_AXE_THUN = 34,
        WEAPON_DAGGER_V = 35,
        WEAPON_DAGGER_S = 36,
        WEAPON_DAGGER_Q = 37,
        WEAPON_DAGGER_V_D = 38,
        WEAPON_DAGGER_S_E = 39,
        WEAPON_DAGGER_Q_S = 40,
        WEAPON_DAGGER_FIRE = 41,
        WEAPON_DAGGER_BLIZ = 42,
        WEAPON_DAGGER_THUN = 43,
        WEAPON_ROD_I = 44,
        WEAPON_ROD_F = 45,
        WEAPON_ROD_V = 46,
        WEAPON_ROD_I_V = 47,
        WEAPON_ROD_F_V = 48,
        WEAPON_ROD_V_IF = 49,
        WEAPON_ROD_FIRE = 50,
        WEAPON_ROD_BLIZ = 51,
        WEAPON_ROD_THUN = 52,
        WEAPON_MONSTER_WEP = 53,
        WEAPON_MONSTER_WEP_WEAK = 54,
        WEAPON_MONSTER_WEP_STRONG = 55,
        WEAPON_MONSTER_MAGIC = 56,
        WEAPON_MONSTER_FIRE = 57,
        WEAPON_MONSTER_BLIZ = 58,
        WEAPON_MONSTER_THUN = 59,
        WEAPON_MAX = 60,

        ARMOR_MAIL = 1001,
        ARMOR_SHIELD = 1002,
        ARMOR_HELM = 1003,
        ARMOR_GLOVE = 1004,
        ARMOR_ROBE = 1005,
        ARMOR_MAIL_S = 1006,
        ARMOR_MAIL_D = 1007,
        ARMOR_MAIL_Q = 1008,
        ARMOR_MAIL_S_V = 1009,
        ARMOR_MAIL_V_S = 1010,
        ARMOR_MAIL_D_Q = 1011,
        ARMOR_MAIL_FIRE = 1012,
        ARMOR_MAIL_BLIZ = 1013,
        ARMOR_MAIL_THUN = 1014,
        ARMOR_SHIELD_V = 1015,
        ARMOR_SHIELD_D = 1016,
        ARMOR_SHIELD_F = 1017,
        ARMOR_SHIELD_V_D = 1018,
        ARMOR_SHIELD_D_Q = 1019,
        ARMOR_SHIELD_F_V = 1020,
        ARMOR_SHIELD_FIRE = 1021,
        ARMOR_SHIELD_BLIZ = 1022,
        ARMOR_SHIELD_THUN = 1023,
        ARMOR_HELM_I = 1024,
        ARMOR_HELM_E = 1025,
        ARMOR_HELM_Q = 1026,
        ARMOR_HELM_I_F = 1027,
        ARMOR_HELM_E_S = 1028,
        ARMOR_HELM_Q_V = 1029,
        ARMOR_HELM_I_F_2 = 1030,
        ARMOR_HELM_FIRE = 1031,
        ARMOR_HELM_BLIZ = 1032,
        ARMOR_HELM_THUN = 1033,
        ARMOR_GLOVE_S = 1034,
        ARMOR_GLOVE_E = 1035,
        ARMOR_GLOVE_I = 1036,
        ARMOR_GLOVE_S_Q = 1037,
        ARMOR_GLOVE_E_F = 1038,
        ARMOR_GLOVE_I_E = 1039,
        ARMOR_GLOVE_FIRE = 1040,
        ARMOR_GLOVE_BLIZ = 1041,
        ARMOR_GLOVE_THUN = 1042,
        ARMOR_ROBE_I = 1043,
        ARMOR_ROBE_F = 1044,
        ARMOR_ROBE_V = 1045,
        ARMOR_ROBE_I_F = 1046,
        ARMOR_ROBE_F_I = 1047,
        ARMOR_ROBE_V_IF = 1048,
        ARMOR_ROBE_FIRE = 1049,
        ARMOR_ROBE_BLIZ = 1050,
        ARMOR_ROBE_THUN = 1051,
        ARMOR_BRACELET_V = 1052,
        ARMOR_BRACELET_S = 1053,
        ARMOR_BRACELET_E = 1054,
        ARMOR_BRACELET_D = 1055,
        ARMOR_BRACELET_Q = 1056,
        ARMOR_BRACELET_I = 1057,
        ARMOR_BRACELET_F = 1058,
        ARMOR_NECKLACE_V_S = 1059,
        ARMOR_NECKLACE_S_E = 1060,
        ARMOR_NECKLACE_E_D = 1061,
        ARMOR_NECKLACE_D_Q = 1062,
        ARMOR_NECKLACE_Q_I = 1063,
        ARMOR_NECKLACE_I_F = 1064,
        ARMOR_NECKLACE_F_V = 1065,
        ARMOR_TALISMAN_GRAV = 1066,
        ARMOR_TALISMAN_POIS = 1067,
        ARMOR_TALISMAN_SLOW = 1068,
        ARMOR_TALISMAN_BLIN = 1069,
        ARMOR_TALISMAN_SLEP = 1070,
        ARMOR_MONSTER_ARM = 1071,
        ARMOR_MONSTER_ARM_MID = 1072,
        ARMOR_MONSTER_ARM_END = 1073,
        ARMOR_PRIN = 1074,
        ARMOR_UNDEAD_HALF = 1075,
        ARMOR_UNDEAD = 1076,
        ARMOR_SHELLARMOR = 1077,
        ARMOR_HARD_SKIN = 1078,
        ARMOR_STONE_SKIN = 1079,
        ARMOR_PLANT = 1080,
        ARMOR_BLOCKHEAD_HALF = 1081,
        ARMOR_BLOCKHEAD = 1082,
        ARMOR_POISON_RESI = 1083,
        ARMOR_WEAK_RESI = 1084,
        ARMOR_GRAV_RESI_HALF = 1085,
        ARMOR_GRAV_RESI = 1086,
        ARMOR_WEAK_FIRE_HALF = 1087,
        ARMOR_WEAK_FIRE = 1088,
        ARMOR_WEAK_BLIZ_HALF = 1089,
        ARMOR_WEAK_BLIZ = 1090,
        ARMOR_WEAK_THUN_HALF = 1091,
        ARMOR_WEAK_THUN = 1092,
        ARMOR_ALL_RESI_HALF = 1093,
        ARMOR_ALL_RESI = 1094,
        ARMOR_ALL_PARAM_1 = 1095,
        ARMOR_ALL_PARAM_2 = 1096,
        ARMOR_BRACELET_BEHEM = 1097,
        ARMOR_BRACELET_MIND = 1098,
        ARMOR_BRACELET_DEATH = 1099,
        ARMOR_BRACELET_DZOM = 1100,
        ARMOR_BRACELET_BRUTAL = 1101,
        ARMOR_MAX = 1102,

        ITEM_POTION = 2001,
        ITEM_HIPOTION = 2002,
        ITEM_ANTIDOTE = 2003,
        ITEM_PERFECTANTIDOTE = 2004,
        ITEM_TORCH = 2005,
        ITEM_PHOENIXTAIL = 2006,
        ITEM_PHOENIXWING = 2007,
        ITEM_MAX = 2008,
    }

    public sealed class Item
    {
        private readonly JArray _data;

        public Item(JArray data)
        {
            _data = data;
        }

        public ItemType Type
        {
            get => _data[0].ToObject<ItemType>();
            set => _data[0] = (int)value;
        }

        public int Level
        {
            get => _data[1].ToObject<int>();
            set => _data[1] = value;
        }
    }
}
